### ISSUE TITLE
Classifier memory usage bug

### ISSUE THREAD

**Issue by flinder** [SMAPPNYU/smapp_stance_classifier#29]
```
(ulmfit) [vis@gpu ulmfit]$ python3 classification.py
cuda:0
Traceback (most recent call last):
  File "classification.py", line 78, in <module>
    res = final(x)
  File "/home/vis/anaconda3/envs/ulmfit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vis/anaconda3/envs/ulmfit/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/vis/anaconda3/envs/ulmfit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vis/smapp_stance_classifier/ulmfit/classifierModel.py", line 64, in forward
    output, hidden = rnn(self.dropout(output) if l!= self.num_layers-1 else output, self.hidden[l])
  File "/home/vis/anaconda3/envs/ulmfit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vis/anaconda3/envs/ulmfit/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 179, in forward
    self.dropout, self.training, self.bidirectional, self.batch_first)
RuntimeError: CUDA out of memory. Tried to allocate 2.13 GiB (GPU 0; 11.91 GiB total capacity; 4.72 GiB already allocated; 2.12 GiB free; 299.41 MiB cached)
```

**Comment by flinder** [comment]
Fixed in 3118a8622ef4e92f434bcec3314fd8a922ed4a12.
